# Build settings
[doc]
# Document name
name = "Main"

# Bundle to use
bundle = "https://data1.fullyjustified.net/tlextras-2022.0r0.tar"

# Output settings
[[output]]
type = "pdf"
name = "Main"
shell_escape = true
preamble = "Main"
